version: '3.8'
services: 
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ChatBotSA:/app/ChatBotSA
    working_dir: /app/ChatBotSA
    ports:
      - "8000:8000"
    network_mode: "bridge"